require("user.plugins_config.lualine")
require("user.plugins_config.cmp")
require("user.plugins_config.treesitter")
require("user.plugins_config.autopairs")
require("user.plugins_config.comment")
require("user.plugins_config.nvim-tree")
require("user.plugins_config.toggleterm")
require("user.plugins_config.telescope")
