# .bash_profile

# Get the aliases and functions
if [ -f ~/.bashrc ]; then
	. ~/.bashrc
fi

# User specific environment and startup programs
#
# Fix Alacritty title bar
export WINIT_UNIX_BACKEND=x11
export PATH="$HOME/.cargo/bin:$PATH"
